FROM icefall/pytorch1.7.1-188:latest

COPY requirements.txt /workspace
RUN pip install -r requirements.txt
RUN pip install pyonmttok websockets
RUN pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

COPY ./icefall /workspace/icefall
COPY ./egs /workspace/egs
COPY ./egs/librispeech/ASR/transducer_emformer_pyonmttok/data-us /data

ENV PYTHONPATH $PYTHONPATH:/workspace/egs/librispeech/ASR/transducer_emformer_pyonmttok:/workspace
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION python

WORKDIR /workspace/egs/librispeech/ASR/transducer_emformer_pyonmttok
# CMD ["python3", "server.py" , "--context-size", "15", "--exp-dir", "exp_ubiqus_context_15_scratch_restart/", "--beam-size", "10"]
CMD ["python3", "server.py" , "--context-size", "15", "--exp-dir", "exp_ubiqus_en_3/", "--beam-size", "10", "--decoding-method", "modified_beam_search"]
