#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

stage=-1
stop_stage=100

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: build monotonic_align lib"
  if [ ! -d vits/monotonic_align/build ]; then
    cd vits/monotonic_align
    python3 setup.py build_ext --inplace
    cd ../../
  else
    log "monotonic_align lib already built"
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Download data"

  # The directory $dl_dir/BZNSYP will contain 3 sub directories:
  #   - PhoneLabeling
  #   - ProsodyLabeling
  #   - Wave

  # If you have pre-downloaded it to /path/to/BZNSYP, you can create a symlink
  #
  #   ln -sfv /path/to/BZNSYP $dl_dir/
  #   touch $dl_dir/BZNSYP/.completed
  #
  if [ ! -d $dl_dir/BZNSYP ]; then
    lhotse download baker-zh $dl_dir
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Prepare baker-zh manifest"
  # We assume that you have downloaded the baker corpus
  # to $dl_dir/BZNSYP
  mkdir -p data/manifests
  if [ ! -e data/manifests/.baker.done ]; then
    lhotse prepare baker-zh $dl_dir/BZNSYP data/manifests
    touch data/manifests/.baker.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Compute spectrogram for baker (may take 3 minutes)"
  mkdir -p data/spectrogram
  if [ ! -e data/spectrogram/.baker.done ]; then
    ./local/compute_spectrogram_baker.py
    touch data/spectrogram/.baker.done
  fi

  if [ ! -e data/spectrogram/.baker-validated.done ]; then
    log "Validating data/spectrogram for baker"
    python3 ./local/validate_manifest.py \
      data/spectrogram/baker_zh_cuts_all.jsonl.gz
    touch data/spectrogram/.baker-validated.done
  fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Prepare tokens for baker-zh (may take 20 seconds)"
  if [ ! -e data/spectrogram/.baker_zh_with_token.done ]; then

    ./local/prepare_tokens_baker_zh.py

    mv -v data/spectrogram/baker_zh_cuts_with_tokens_all.jsonl.gz \
      data/spectrogram/baker_zh_cuts_all.jsonl.gz

    touch data/spectrogram/.baker_zh_with_token.done
  fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 5: Split the baker-zh cuts into train, valid and test sets (may take 25 seconds)"
  if [ ! -e data/spectrogram/.baker_zh_split.done ]; then
    lhotse subset --last 600 \
      data/spectrogram/baker_zh_cuts_all.jsonl.gz \
      data/spectrogram/baker_zh_cuts_validtest.jsonl.gz
    lhotse subset --first 100 \
      data/spectrogram/baker_zh_cuts_validtest.jsonl.gz \
      data/spectrogram/baker_zh_cuts_valid.jsonl.gz
    lhotse subset --last 500 \
      data/spectrogram/baker_zh_cuts_validtest.jsonl.gz \
      data/spectrogram/baker_zh_cuts_test.jsonl.gz

    rm data/spectrogram/baker_zh_cuts_validtest.jsonl.gz

    n=$(( $(gunzip -c data/spectrogram/baker_zh_cuts_all.jsonl.gz | wc -l) - 600 ))
    lhotse subset --first $n  \
      data/spectrogram/baker_zh_cuts_all.jsonl.gz \
      data/spectrogram/baker_zh_cuts_train.jsonl.gz
      touch data/spectrogram/.baker_zh_split.done
  fi
fi

if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
  log "Stage 6: Generate token file"
  if [ ! -e data/tokens.txt ]; then
    ./local/prepare_token_file.py --tokens data/tokens.txt
  fi
fi
