#!/usr/bin/env bash

# 参数部分  -----------------------------------------------------------------------------------------------------------------
stage=5
stop_stage=5
export CUDA_VISIBLE_DEVICES=0
# export MODEL_TYPE="zipformer_s_55"
# export MODEL_TYPE="zipformer_m_55"
export MODEL_TYPE="zipformer_l_56"
: ${embedding_layers:="1,7"}      # 若未定义则默认0 ~ 7
: ${num_codebooks:="16,16"}     # 若未定义则默认2,4,8,16
IFS=',' read -ra embedding_layer <<< "$embedding_layers"  # 分割字符串到数组
IFS=',' read -ra num_codebook <<< "$num_codebooks"
exp_dir=./mvq_kd_zipformer/exp11
mkdir -p $exp_dir
# use_extracted_codebook=True
use_extracted_codebook=False
teacher_model_id=zipformer_l_56
# teacher_model_id=zipformer_s_55
# teacher_model_id=zipformer_m_55
use_mul_tea=True
# use_mul_tea=False

. shared/parse_options.sh || exit 1
log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}
if [ ! -d ./data/fbank ]; then
  log "This script assumes ./data/fbank is already generated by prepare.sh"
  exit 1
fi

# 提取码本索引部分 ----------------------------------------------------------------------------------------------------------
if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then

  # --num-utts-extracted 360294   part 360182
  # --embedding-dim layer7:(256 s    512 m    768 l)   layer1: 192
    ./mvq_kd_zipformer/extract_codebook_index.py \
      --kd-exp-dir $exp_dir \
      --embedding-layer ${embedding_layer[1]} \
      --num-utts 2000 \
      --num-codebooks ${num_codebook[1]} \
      --max-duration 300 \
      --teacher-model-id $teacher_model_id \
      --spec-aug-time-warp-factor -1 \
      --embedding-dim 768 \
      --num-utts-extracted 360294 \
      --use-extracted-codebook $use_extracted_codebook

fi

# 聚合多层码本索引部分----------------------------------------------------------------------------------------------------------
if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
    # part 1: combine single teacher layers CI        part 2: combine multiple teacher's CI
  ./mvq_kd_zipformer/combine_jsonl.py \
    --output-path $exp_dir \
    --teacher-model-id $teacher_model_id \
    --use-mul-tea $use_mul_tea

fi

# 教师模型样本级置信度及锐度提取部分------------------------------------------------------------------------------------------------------
if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then

  # ./mvq_kd_zipformer/train_m_confidence.py \
  #   --manifest-dir $exp_dir/combined_${embedding_layer[0]}_${embedding_layer[1]} \
  #   --num-epochs 56 \
  #   --start-epoch 56 \
  #   --max-duration 300 \
  #   --exp-dir $exp_dir/zipformer_m\
  #   --lang-dir data/lang_char \
  #   --context-size 1 \
  #   --teacher-model-id $teacher_model_id

  # ./mvq_kd_zipformer/train_s_confidence.py \
  #   --manifest-dir $exp_dir/combined_${embedding_layer[0]}_${embedding_layer[1]} \
  #   --num-epochs 56 \
  #   --start-epoch 56 \
  #   --max-duration 300 \
  #   --exp-dir $exp_dir \
  #   --lang-dir data/lang_char \
  #   --context-size 1 \
  #   --teacher-model-id $teacher_model_id

  # ./mvq_kd_zipformer/train_l_confidence.py \
  #   --manifest-dir $exp_dir/combined_${embedding_layer[0]}_${embedding_layer[1]} \
  #   --num-epochs 57 \
  #   --start-epoch 57 \
  #   --max-duration 300 \
  #   --exp-dir $exp_dir \
  #   --lang-dir data/lang_char \
  #   --context-size 1 \
  #   --teacher-model-id $teacher_model_id

  # 聚合多教师模型样本级置信度及锐度
  ./mvq_kd_zipformer/combine_logs.py \
    --output-path $exp_dir
fi

# 训练学生模型部分----------------------------------------------------------------------------------------------------------
if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  # Example training script.
  # Note: it's better to set spec-aug-time-warpi-factor=-1
  WORLD_SIZE=$(echo ${CUDA_VISIBLE_DEVICES} | awk '{n=split($1, _, ","); print n}')
  # --manifest-dir $exp_dir/${embedding_layer}_cb${num_codebooks} \
  # --exp-dir $exp_dir/student/multilayer_${embedding_layer[0]}_${embedding_layer[1]}_cb${num_codebook[0]}_
  # --exp-dir $exp_dir/student/zipformer_xs_squeeze/fraction15/mtml

  ./mvq_kd_zipformer/train_xs_new.py \
    --manifest-dir $exp_dir/combined_${embedding_layer[0]}_${embedding_layer[1]} \
    --spec-aug-time-warp-factor -1 \
    --max-duration 300 \
    --world-size ${WORLD_SIZE} \
    --num-epochs 60 \
    --start-epoch 17 \
    --save-every-n 100000 \
    --exp-dir $exp_dir/student/xs_full_dataset/st-m \
    --distillation-layer $embedding_layers \
    --num-codebooks $num_codebooks \
    --enable-distillation True \
    --enable-multilayer-distillation True \
    --use-mul-tea use_mul_tea \
    --codebook-loss-scale 1.0 \
    --layers-weight-opt "uncertainty2" \
    --tea-weight-opt "test-m" \
    --data-fraction 1
fi

# 解码学生模型部分----------------------------------------------------------------------------------------------------------
if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
  # Results should be similar to:
  # errs-test-clean-beam_size_4-epoch-20-avg-10-beam-4.txt:%WER = 5.67
  # errs-test-other-beam_size_4-epoch-20-avg-10-beam-4.txt:%WER = 15.60
  ./mvq_kd_zipformer/decode_xs.py \
    --decoding-method "greedy_search" \
    --epoch 60 \
    --avg 10 \
    --max-duration 750 \
    --exp-dir $exp_dir/student/xs_full_dataset/st-s \
    --lang-dir data/lang_char \
    --context-size 1 \
    --distillation-layer $embedding_layers \
    --num-codebooks $num_codebooks \
    --layers-weight-opt "uncertainty2" \
    --enable-distillation True
fi

