#!/bin/bash

echo "허깅페이스 모델 업로드 가이드"
echo "================================"
echo ""
echo "1. 허깅페이스 토큰 생성 및 로그인:"
echo "   huggingface-cli login"
echo ""
echo "2. 모델 업로드 실행:"
echo "   python upload_to_huggingface.py"
echo ""
echo "3. 필요한 정보:"
echo "   - Repository name (예: jenny/icefall-conformer-ctc-librispeech)"
echo "   - Hugging Face token (Write 권한 필요)"
echo "   - Private repository 여부"
echo ""
echo "4. 업로드될 파일들:"
echo "   - best-valid-loss.pt (모델 체크포인트)"
echo "   - README.md (모델 카드)"
echo "   - config.json (모델 설정)"
echo "   - inference_example.py (사용 예제)"
echo "   - requirements.txt (의존성 패키지)"
echo ""
echo "업로드를 시작하려면:"
echo "python upload_to_huggingface.py"
