# see also
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Build docker image
on:
  push:
    branches:
      - docker

  workflow_dispatch:

concurrency:
  group: build_docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-doc:
    name: build docker image
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Rename
        shell: bash
        run: |
          ls -lh
          ls -lh ./docker
          mv -v ./docker/torch1.13.0-cuda11.6-cudnn8.dockerfile ./Dockerfile
          ls -lh

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: k2fsa/icefall:torch1.13.0-cuda11.6
