name: Build docker image
on:
  push:
    branches:
      - docker

  workflow_dispatch:

concurrency:
  group: build_docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-doc:
    name: build docker image
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./torch1.13.0-cuda11.6-cudnn8.Dockerfile
          push: true
          tags: k2fsa/icefall:torch1.13.0-cuda11.6
