name: run-ptb-rnn-lm-training

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

  schedule:
    - cron: "50 15 * * *"

  workflow_dispatch:

concurrency:
  group: run_ptb_rnn_lm_training-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_build_matrix:
    if: github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          python ./.github/scripts/docker/generate_build_matrix.py --python-version "3.10" --min-torch-version "2.2.0"
          MATRIX=$(python ./.github/scripts/docker/generate_build_matrix.py --python-version "3.10" --min-torch-version "2.2.0")
          echo "::set-output name=matrix::${MATRIX}"

  run_ptb_rnn_lm_training:
    if: github.event.label.name == 'ready' || github.event.label.name == 'rnnlm' || github.event_name == 'push' || github.event_name == 'schedule'
    needs: generate_build_matrix
    name: py${{ matrix.python-version }} torch${{ matrix.torch-version }} v${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare data
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/${{ github.repository_owner }}/icefall:cpu-py${{ matrix.python-version }}-torch${{ matrix.torch-version }}-v${{ matrix.version }}
            options: |
              --volume ${{ github.workspace }}/:/icefall
            shell: bash
            run: |
              export PYTHONPATH=/icefall:$PYTHONPATH
              cd /icefall
              git config --global --add safe.directory /icefall

              python3 -m pip install onnxscript lilcom
              python3 -c "import torch; v=torch.__version__.split('.'); exit(0 if (int(v[0]),int(v[1])) >= (2,9) else 1)" && python3 -m pip install torchcodec==0.14.0+cpu -f https://download.pytorch.org/whl/torchcodec || true

              python3 -m torch.utils.collect_env
              python3 -m k2.version
              pip list

              cd egs/ptb/LM
              ./prepare.sh

      - name: Run training
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/${{ github.repository_owner }}/icefall:cpu-py${{ matrix.python-version }}-torch${{ matrix.torch-version }}-v${{ matrix.version }}
            options: |
              --volume ${{ github.workspace }}/:/icefall
            shell: bash
            run: |
              export PYTHONPATH=/icefall:$PYTHONPATH
              cd /icefall
              git config --global --add safe.directory /icefall

              python3 -m pip install onnxscript lilcom
              python3 -c "import torch; v=torch.__version__.split('.'); exit(0 if (int(v[0]),int(v[1])) >= (2,9) else 1)" && python3 -m pip install torchcodec==0.14.0+cpu -f https://download.pytorch.org/whl/torchcodec || true

              cd egs/ptb/LM
              ./train-rnn-lm.sh --world-size 1 --num-epochs 5 --use-epoch 4 --use-avg 2

      - name: Upload pretrained models
        uses: actions/upload-artifact@v4
        if: matrix.torch-version == '2.13.0' && (github.event.label.name == 'ready' || github.event.label.name == 'rnnlm' || github.event_name == 'push' || github.event_name == 'schedule')
        with:
          name: python-${{ matrix.python-version }}-ubuntu-rnn-lm-ptb
          path: egs/ptb/LM/my-rnnlm-exp/
