name: run-gigaspeech-zipformer-2023-10-17
# zipformer

on:
  push:
    branches:
      - master

  pull_request:
    types: [labeled]

  schedule:
    # minute (0-59)
    # hour (0-23)
    # day of the month (1-31)
    # month (1-12)
    # day of the week (0-6)
    # nightly build at 15:50 UTC time every day
    - cron: "50 15 * * *"

  workflow_dispatch:

concurrency:
  group: run_gigaspeech_2023_10_17_zipformer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_build_matrix:
    if: github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python ./.github/scripts/docker/generate_build_matrix.py --python-version "3.10" --min-torch-version "2.2.0"
          MATRIX=$(python ./.github/scripts/docker/generate_build_matrix.py --python-version "3.10" --min-torch-version "2.2.0")
          echo "::set-output name=matrix::${MATRIX}"

  run_gigaspeech_2023_10_17_zipformer:
    if: github.event.label.name == 'zipformer' || github.event.label.name == 'ready' || github.event.label.name == 'run-decode' || github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: generate_build_matrix
    name: py${{ matrix.python-version }} torch${{ matrix.torch-version }} v${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inference with pre-trained model
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/${{ github.repository_owner }}/icefall:cpu-py${{ matrix.python-version }}-torch${{ matrix.torch-version }}-v${{ matrix.version }}
            options: |
              --volume ${{ github.workspace }}/:/icefall
              -e GITHUB_EVENT_NAME=${{ github.event_name }}
              -e GITHUB_EVENT_LABEL_NAME=${{ github.event.label.name }}
              -e HF_TOKEN=${{ secrets.HF_TOKEN }}
            shell: bash
            run: |
              export PYTHONPATH=/icefall:$PYTHONPATH
              cd /icefall
              git config --global --add safe.directory /icefall

              python3 -m pip install onnxscript lilcom torchcodec

              python3 -m torch.utils.collect_env
              python3 -m k2.version
              pip list

              apt-get install -y -q git-lfs tree

              .github/scripts/run-gigaspeech-zipformer-2023-10-17.sh

      - name: upload model to https://github.com/k2-fsa/sherpa-onnx
        if: matrix.torch-version == '2.13.0'
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.tar.bz2
          overwrite: true
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: asr-models

      - name: Display decoding results for gigaspeech zipformer
        if: matrix.torch-version == '2.13.0' && (github.event_name == 'schedule' || github.event.label.name == 'run-decode' || github.event_name == 'workflow_dispatch')
        shell: bash
        run: |
          cd egs/gigaspeech/ASR/
          tree ./zipformer/exp

          cd zipformer
          echo "results for zipformer"
          echo "===greedy search==="
          find exp/greedy_search -name "log-*" -exec grep -n --color "best for test-clean" {} + | sort -n -k2
          find exp/greedy_search -name "log-*" -exec grep -n --color "best for test-other" {} + | sort -n -k2

      - name: Upload decoding results for gigaspeech zipformer
        uses: actions/upload-artifact@v4
        if: matrix.torch-version == '2.13.0' && (github.event_name == 'schedule' || github.event.label.name == 'run-decode' || github.event_name == 'workflow_dispatch')
        with:
          name: torch-${{ matrix.torch-version }}-python-${{ matrix.python-version }}-ubuntu-latest-cpu-zipformer-2022-11-11
          path: egs/gigaspeech/ASR/zipformer/exp/
