name: Run docker image
on:
  push:
    branches:
      - docker2
  workflow_dispatch:

concurrency:
  group: run_docker_image-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-docker-image:
    name: run docker
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: k2fsa/icefall:torch1.13.0-cuda11.6
            run: |
              uname -a
              python3 --version
              python3 -m torch.utils.collect_env
              # python3 -m k2.version
              python3 -c "import lhotse; print(lhotse.__version__)"
              # python3 -c "import kaldifeat; print(kaldifeat.__version__)"
              nvcc --version
              which nvcc
              find /usr/ -name libcuda.so*
              find /opt/ -name libcuda.so*
              find / -name libcuda.so* 2>/dev/null
